1. Initialize an all one array with size 2X2.


In [ ]:
array = [[0, 0], [0, 0]]


2.	Initialize an all one array with size 4X2.

In [ ]:
array = [[2,5] for _ in range(4)]
print(array)

[[2, 5], [2, 5], [2, 5], [2, 5]]


3.	Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np

shape = (3, 4)
fill_value = 10

array = np.full(shape, fill_value)

print(array)


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


4.	Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np

given_array = np.array([[3,4,5], [8,7,6]])
zeros_array = np.zeros_like(given_array)

print(zeros_array)


[[0 0 0]
 [0 0 0]]


5.	Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}


In [ ]:
import numpy as np

given_array = np.array([[2, 4, 8], [10, 5, 9]])
ones_array = np.ones_like(given_array)

print(ones_array)


[[1 1 1]
 [1 1 1]]


6.	For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

new_list = [9, 12, 7, 2]

# Convert to a NumPy array
numpy_array = np.array(new_list)

print(numpy_array)


[ 9 12  7  2]


2.1.	Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np

array = np.arange(10, 50)

print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2.2.	Create a 3X3 matrix with values ranging from 0 to 8.

In [ ]:
import numpy as np

# Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


2.3.	Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
import numpy as np
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2.4.	Create a random array of size 30 and find the mean of the array.

In [ ]:
import numpy as np
# Create a random array of size 30
random_array = np.random.rand(30)

mean_value = np.mean(random_array)

print("Random Array:", random_array)
print("Mean of the Array:", mean_value)


Random Array: [0.89635266 0.93452271 0.54687706 0.0797811  0.33575731 0.78050171
 0.61152221 0.64012913 0.6223487  0.47320059 0.49828859 0.76925748
 0.16362642 0.21021473 0.35916608 0.18396406 0.0182993  0.15079445
 0.22061872 0.5105251  0.65886384 0.91359948 0.81941639 0.12528154
 0.40507835 0.60933577 0.91296517 0.30147693 0.53036499 0.77358826]
Mean of the Array: 0.5018572949811126


2.5.	Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np

# Create a 10x10 array with random values
random_array = np.random.rand(10, 10)

min_value = np.min(random_array)
max_value = np.max(random_array)

print("Random Array:\n", random_array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


Random Array:
 [[5.99514147e-01 3.69565729e-01 1.27900085e-01 2.54591204e-01
  4.31035328e-01 8.82399699e-01 5.93003325e-01 2.81621944e-01
  3.63400504e-02 5.64566300e-01]
 [4.89999351e-01 4.74293905e-01 2.59938048e-01 6.67333358e-01
  6.20011064e-01 7.65057947e-01 9.87554134e-01 6.01913238e-01
  3.70428209e-06 7.90041916e-01]
 [5.50806352e-01 5.12087492e-01 7.54895210e-01 4.53589134e-01
  4.69179326e-01 9.60275239e-01 7.17669070e-01 5.07971755e-01
  2.81413833e-01 1.93638037e-01]
 [2.06174517e-01 7.70431539e-01 7.23219212e-01 2.52153789e-01
  8.92481170e-01 6.83074247e-01 6.56137568e-01 5.59819347e-01
  3.66200442e-01 8.32186904e-01]
 [1.59459932e-01 2.65122618e-01 7.37321379e-01 4.88240198e-01
  4.24944925e-01 6.19346984e-02 1.67146908e-01 5.46282007e-01
  2.29433577e-01 1.43074227e-04]
 [4.39303360e-01 5.19431538e-01 1.67596551e-01 4.06788496e-01
  3.17743815e-01 5.19189036e-01 4.69990512e-01 4.51608868e-01
  4.76338437e-01 5.87780782e-01]
 [8.47419784e-01 6.83013923e-01 9.60361731e

2.6.	Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
import numpy as np
import numpy as np

zero_array = np.zeros(10)   # Create a zero array of size 10
zero_array[4] = 1           # Replace the 5th element (index 4) with 1

print(zero_array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


2.7.	Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]

print(reversed_arr)


[0 4 0 0 2 1]


2.8.	Create a 2d array with 1 on border and 0 inside

In [ ]:
import numpy as np

# Create a 2D array with 1 on the border and 0 inside
size = 4
array = np.ones((size, size))

# Set the inside elements to 0
array[1:-1, 1:-1] = 0

print(array)


[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


2.9.	Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# Create an 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]); Complete all the task using numpy:

3.1. Add the two array.

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Add the two arrays
sum_array = x + y

print(sum_array)


[[ 6  8]
 [10 13]]


x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]); Complete all the task using numpy:

3.2. Subtract the two array


In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

subtract_array = x - y

print(subtract_array)

[[-4 -4]
 [-4 -3]]


x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]); Complete all the task using numpy:

3.3. Multiply the array with any integers of your choice.


In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

integer = 4

# Multiply the arrays by the integer
x_multiplied = x * integer
y_multiplied = y * integer

print("x multiplied by 2:\n", x_multiplied)
print("y multiplied by 2:\n", y_multiplied)


x multiplied by 2:
 [[ 4  8]
 [12 20]]
y multiplied by 2:
 [[20 24]
 [28 32]]


x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]); Complete all the task using numpy:

3.4.Find the square of each element of the array

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Square of each element in the arrays
x_squared = x ** 2
y_squared = y ** 2
v_squared = v ** 2
w_squared = w ** 2

print("Square of x:\n", x_squared)
print("Square of y:\n", y_squared)
print("Square of v:\n", v_squared)
print("Square of w:\n", w_squared)


Square of x:
 [[ 1  4]
 [ 9 25]]
Square of y:
 [[25 36]
 [49 64]]
Square of v:
 [ 81 100]
Square of w:
 [121 144]


3.5.	Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Calculate dot products
v_and_w = np.dot(v, w)
x_and_v = np.dot(x, v)
x_and_y = np.dot(x, y)

# Print the results
print("Dot product between v and w:", v_and_w)
print("Dot product between x and v:\n", x_and_v)
print("Dot product between x and y:\n", x_and_y)


Dot product between v and w: 219
Dot product between x and v:
 [29 77]
Dot product between x and y:
 [[19 22]
 [50 58]]


3.6.	Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.*italicized text*

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Concatenate x and y along rows using np.concatenate
concat_x_y = np.concatenate((x, y), axis=0)

# Concatenate v and w along columns using np.stack
stack_v_w = np.stack((v, w), axis=1)

# Print the results
print("Concatenation of x and y along rows using np.concatenate:\n", concat_x_y)
print("Concatenation of v and w along columns using np.stack:\n", stack_v_w)


Concatenation of x and y along rows using np.concatenate:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns using np.stack:
 [[ 9 11]
 [10 12]]


3.7.	Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])

concat_xv = np.concatenate(x,v)
print(concat_xv)

TypeError: only integer scalar arrays can be converted to a scalar index

4.1. A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]); Prove following with Numpy:
1.	Prove A.A−1 = I.
2.	Prove AB ̸= BA.
3.	Prove (AB)T = BTAT.

    

In [ ]:
#Problem - 4: Matrix Operations:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A.A⁻¹ = I
A_inv = np.linalg.inv(A)
I = np.eye(2)
print("Multiplication of A and inverse of A):")
print(np.dot(A, A_inv))
print("\nIdentity matrix:")
print(I)

# 2. Prove AB ≠ BA
AB = np.dot(A,B)
print("A.B : \n", AB, "\n")
BA = np.dot(B,A)
print("B.A : \n", BA, "\n")
print("AB == BA ? : ", np.allclose(AB,BA), "\n")

# 3. Prove (AB)ᵀ = BᵀAᵀ
trans_of_AB = np.transpose(AB)
print("Transpose of AB: \n",trans_of_AB, "\n")
trans_of_B = np.transpose(B)
trans_of_A = np.transpose(A)
A_trans_b_trans = np.dot(trans_of_B, trans_of_A)
print("A transpose.B transpose : \n", A_trans_b_trans, "\n")
print("Is (AB)ᵀ equal to BᵀAᵀ ?: ", np.allclose(trans_of_AB, A_trans_b_trans), "\n")

Multiplication of A and inverse of A):
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Identity matrix:
[[1. 0.]
 [0. 1.]]
A.B : 
 [[23 13]
 [51 29]] 

B.A : 
 [[36 44]
 [13 16]] 

AB == BA ? :  False 

Transpose of AB: 
 [[23 51]
 [13 29]] 

A transpose.B transpose : 
 [[23 51]
 [13 29]] 

Is (AB)ᵀ equal to BᵀAᵀ ?:  True 



4.2.	Solve the following system of Linear equation using Inverse Methods.
                
                 2x − 3y + z = −1
                 x − y + 2z = −3
                 3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}



In [ ]:
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

# Step 1: Determinant of A
det_A = (A[0, 0] * (A[1, 1] * A[2, 2] - A[1, 2] * A[2, 1]) -
         A[0, 1] * (A[1, 0] * A[2, 2] - A[1, 2] * A[2, 0]) +
         A[0, 2] * (A[1, 0] * A[2, 1] - A[1, 1] * A[2, 0]))

print("Determinant of A:", det_A)

# Step 2: Cofactor matrix
cofactor_matrix = np.array([
    [(A[1, 1] * A[2, 2] - A[1, 2] * A[2, 1]), -(A[1, 0] * A[2, 2] - A[1, 2] * A[2, 0]), (A[1, 0] * A[2, 1] - A[1, 1] * A[2, 0])],
    [-(A[0, 1] * A[2, 2] - A[0, 2] * A[2, 1]), (A[0, 0] * A[2, 2] - A[0, 2] * A[2, 0]), -(A[0, 0] * A[2, 1] - A[0, 1] * A[2, 0])],
    [(A[0, 1] * A[1, 2] - A[0, 2] * A[1, 1]), -(A[0, 0] * A[1, 2] - A[0, 2] * A[1, 0]), (A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0])]
])

Determinant of A: -19


4.3. Solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}


In [ ]:
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

# Inverse of A using np.linalg.inv
A_inv = np.linalg.inv(A)

# X = A⁻¹B
X = np.dot(A_inv, B)

print("Inverse of A:\n", A_inv)
print("\nSolution (x, y, z):", X)

Inverse of A:
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution (x, y, z): [ 2.  1. -2.]


4.2 Experiment: How Fast is Numpy?
4.2.1 Element-wise Addition:

In [ ]:
import time

list1=[x for x in range(1,100000)]
list2=[y for y in range(1,100000)]

print("1. Element-wise Addition: \n")
start_at = time.time()
sum1 = [list1[x] + list2[x] for x in range(len(list1))]
end_at = time.time()
print("Time taken for this operation using Python Lists is: ", end_at-start_at, "seconds.\n")


arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start_at = time.time()
sum2 = arr1 + arr2
end_at = time.time()
print("Time taken for this operation using NumPy Arrays is:", end_at-start_at, "seconds.")

1. Element-wise Addition: 

Time taken for this operation using Python Lists is:  0.011311769485473633 seconds.

Time taken for this operation using NumPy Arrays is: 0.0018627643585205078 seconds.


4.2.2 Element-wise Multiplication

In [ ]:
# 2. Element-wise Multiplication:

list1=[x for x in range(1,10000)]
list2=[y for y in range(1,100000)]

print("Element-wise Multiplicatio: \n")
start_at = time.time()
product1 = [list1[x] * list2[x] for x in range(len(list1))]
end_at = time.time()
print("Time taken for this operation using Python Lists is: ", end_at-start_at, "seconds.\n")


arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start_at = time.time()
product2 = arr1*arr2
end_at = time.time()
print("Time taken for this operation using NumPy Arrays is:", end_at - start_at, "seconds")

Element-wise Multiplicatio: 

Time taken for this operation using Python Lists is:  0.00020551681518554688 seconds.

Time taken for this operation using NumPy Arrays is: 0.0023610591888427734 seconds


4.2.3 Dot Product:

In [ ]:
# 3. Dot Product :
list1=[x for x in range(1,100000)]
list2=[y for y in range(1,100000)]

print("Dot product: \n")
start_at = time.time()
product1 = [list1[x] * list2[x] for x in range(len(list1))]
end_at = time.time()
print("Time taken for this operation using Python Lists is: ", end_at-start_at, "seconds.\n")


arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start_at = time.time()
product2 = np.dot(arr1, arr2)
end_at = time.time()
print("Time taken using NumPy arrays:", end_at - start_at, "seconds")

Dot product: 

Time taken for this operation using Python Lists is:  0.010224342346191406 seconds.

Time taken using NumPy arrays: 0.0007948875427246094 seconds


4.2.4 Matrix Multiplication

In [ ]:
print("4. Matrix Multiplication")
size = 100

# Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
matrix1 = [[x for x in range(size)] for _ in range(size)]
matrix2 = [[y for y in range(size)] for _ in range(size)]

start_time = time.time()
result_matrix = [[sum(i * j for i, j in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
end_time = time.time()
print(f"Time taken by Python Lists: {end_time - start_time:.5f} seconds")

# Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)

start_time = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
print(f"Time taken by numpy: {end_time - start_time:.5f} seconds")

4. Matrix Multiplication
Time taken by Python Lists: 0.06934 seconds
Time taken by numpy: 0.00086 seconds
